# Nomor 1

In [13]:
import numpy as np

# buat vektor x_np dengan ukuran 3x1
x_np = np.array([[13], [17], [30]])
print(x_np)

[[13]
 [17]
 [30]]


In [14]:
# buat vektor y_np dengan ukuran 3x1
y_np = np.array([[18], [22], [40]])
print(y_np)

[[18]
 [22]
 [40]]


In [15]:
# hitung panjang vektor x_np
len(x_np)

3

In [16]:
# tampilkan ukuran vektor x_np
x_np.shape

(3, 1)

In [17]:
# tampilkan tipe data dari vektor x_np
x_np.dtype

dtype('int64')

In [18]:
# akses elemen pertama dari vektor x_np
x_np[0]

array([13])

In [19]:
# tampilkan tipe data elemen pertama dari vektor x_np
x_np[0].dtype

dtype('int64')

# Nomor 2

In [23]:
# lakukan transpose pada vektor x_np dan simpan pada variabel x_t
x_t = x_np.T
print(x_t)

[[13 17 30]]


In [24]:
# tampilkan ukuran dari vektor x_t
x_t.shape

(1, 3)

In [25]:
# lakukan transpose pada vektor y_np dan simpan pada variabel y_t
y_t = y_np.T
print(y_t)

[[18 22 40]]


## Nomor 3


### Pytorch

In [34]:
import torch as pt

# buat vektor x_pt dengan ukuran 3x1 menggunakan pytorch dan ukuran dari vektor x_pt
x_pt = pt.tensor([13, 17, 30])
print(x_pt)
x_pt.shape

tensor([13, 17, 30])


torch.Size([3])

In [27]:
# buat vektor y_pt dengan ukuran 3x1 menggunakan pytorch dan ukuran dari vektor y_pt
y_pt = pt.tensor([18, 22, 40])
print(y_pt)
y_pt.shape

tensor([18, 22, 40])


torch.Size([3])

In [36]:
# lakukan transpose pada vektor x_pt dan simpan pada variabel x_pT
x_pT = x_pt.T
print(x_pT)

tensor([13, 17, 30])


### Tensorflow

In [31]:
import tensorflow as tf

# buat vektor x_pt dengan ukuran 3x1 menggunakan tensorflow dan ukuran dari vektor x_pt
x_tf = tf.Variable([13, 17, 30], dtype = tf.int32)
print(x_tf)
x_tf.shape

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([13, 17, 30], dtype=int32)>


TensorShape([3])

In [32]:
# buat vektor y_pt dengan ukuran 3x1 menggunakan tensorflow dan ukuran dari vektor y_pt
y_tf = tf.Variable([18, 22, 40], dtype = tf.int32)
print(y_tf)
y_tf.shape

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([18, 22, 40], dtype=int32)>


TensorShape([3])

In [33]:
# lakukan transpose pada vektor x_tf dan simpan pada variabel x_tF
x_tF = tf.transpose(x_tf)
print(x_tF)
x_tF.shape

tf.Tensor([13 17 30], shape=(3,), dtype=int32)


TensorShape([3])